[package]
name = "faststl"
version = "0.1.0"
edition = "2021"

[lib]
name = "faststl"
crate-type = ["cdylib"]

[dependencies]
stlrs = { path = ".." }
pyo3 = { version = "0.18.1", features = ["extension-module"] }
numpy = "0.18.0"
